export const elementsData = [
  {
    Name: "Hydrogen",
    Symbol: "H",
    AtomicNumber: 1,
    AtomicMass: 1.008,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Gas",
  },
  {
    Name: "Helium",
    Symbol: "He",
    AtomicNumber: 2,
    AtomicMass: 4.0026,
    Classification: "Noble_gases",
    StateOfMatter: "Gas",
  },
  {
    Name: "Lithium",
    Symbol: "Li",
    AtomicNumber: 3,
    AtomicMass: 6.94,
    Classification: "Alkali_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Beryllium",
    Symbol: "Be",
    AtomicNumber: 4,
    AtomicMass: 9.0122,
    Classification: "Alkali_earth_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Boron",
    Symbol: "B",
    AtomicNumber: 5,
    AtomicMass: 10.81,
    Classification: "Post-transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Carbon",
    Symbol: "C",
    AtomicNumber: 6,
    AtomicMass: 12.011,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Solid",
  },
];
