export const elementsData = [
  {
    Name: "Hydrogen",
    Symbol: "H",
    AtomicNumber: 1,
    AtomicMass: 1.008,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Gas",
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    Name: "Helium",
    Symbol: "He",
    AtomicNumber: 2,
    AtomicMass: 4.0026,
    Classification: "Noble_gases",
    StateOfMatter: "Gas",
  },
  {
    Name: "Lithium",
    Symbol: "Li",
    AtomicNumber: 3,
    AtomicMass: 6.94,
    Classification: "Alkali_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Beryllium",
    Symbol: "Be",
    AtomicNumber: 4,
    AtomicMass: 9.0122,
    Classification: "Alkali_earth_metals",
    StateOfMatter: "Solid",
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    Name: "Boron",
    Symbol: "B",
    AtomicNumber: 5,
    AtomicMass: 10.81,
    Classification: "Metalloids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Carbon",
    Symbol: "C",
    AtomicNumber: 6,
    AtomicMass: 12.011,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Nitrogen",
    Symbol: "N",
    AtomicNumber: 7,
    AtomicMass: 14.007,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Gas",
  },
  {
    Name: "Oxygen",
    Symbol: "O",
    AtomicNumber: 8,
    AtomicMass: 15.999,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Gas",
  },
  {
    Name: "Fluorine",
    Symbol: "F",
    AtomicNumber: 9,
    AtomicMass: 18.998,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Gas",
  },
  {
    Name: "Neon",
    Symbol: "Ne",
    AtomicNumber: 10,
    AtomicMass: 20.18,
    Classification: "Noble_gases",
    StateOfMatter: "Gas",
  },
  {
    Name: "Sodium",
    Symbol: "Na",
    AtomicNumber: 11,
    AtomicMass: 22.99,
    Classification: "Alkali_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Magnesium",
    Symbol: "Mg",
    AtomicNumber: 12,
    AtomicMass: 24.305,
    Classification: "Alkali_earth_metals",
    StateOfMatter: "Solid",
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    Name: "Aluminium",
    Symbol: "Al",
    AtomicNumber: 13,
    AtomicMass: 26.982,
    Classification: "Post_transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Silicon",
    Symbol: "Si",
    AtomicNumber: 14,
    AtomicMass: 28.085,
    Classification: "Metalloids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Phosphorus",
    Symbol: "P",
    AtomicNumber: 15,
    AtomicMass: 30.974,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Sulfur",
    Symbol: "S",
    AtomicNumber: 16,
    AtomicMass: 32.06,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Chlorine",
    Symbol: "Cl",
    AtomicNumber: 17,
    AtomicMass: 35.45,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Gas",
  },
  {
    Name: "Argon",
    Symbol: "Ar",
    AtomicNumber: 18,
    AtomicMass: 39.948,
    Classification: "Noble_gases",
    StateOfMatter: "Gas",
  },
  {
    Name: "Potassium",
    Symbol: "K",
    AtomicNumber: 19,
    AtomicMass: 39.098,
    Classification: "Alkali_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Calcium",
    Symbol: "Ca",
    AtomicNumber: 20,
    AtomicMass: 40.078,
    Classification: "Alkali_earth_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Scandium",
    Symbol: "Sc",
    AtomicNumber: 21,
    AtomicMass: 44.956,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Titanium",
    Symbol: "Ti",
    AtomicNumber: 22,
    AtomicMass: 47.867,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Vanadium",
    Symbol: "V",
    AtomicNumber: 23,
    AtomicMass: 50.942,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Chromium",
    Symbol: "Cr",
    AtomicNumber: 24,
    AtomicMass: 51.996,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Manganese",
    Symbol: "Mn",
    AtomicNumber: 25,
    AtomicMass: 54.938,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Iron",
    Symbol: "Fe",
    AtomicNumber: 26,
    AtomicMass: 55.845,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Cobalt",
    Symbol: "Co",
    AtomicNumber: 27,
    AtomicMass: 58.933,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Nickel",
    Symbol: "Ni",
    AtomicNumber: 28,
    AtomicMass: 58.693,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Copper",
    Symbol: "Cu",
    AtomicNumber: 29,
    AtomicMass: 63.546,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Zinc",
    Symbol: "Zn",
    AtomicNumber: 30,
    AtomicMass: 65.38,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Gallium",
    Symbol: "Ga",
    AtomicNumber: 31,
    AtomicMass: 69.723,
    Classification: "Post_transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Germanium",
    Symbol: "Ge",
    AtomicNumber: 32,
    AtomicMass: 72.63,
    Classification: "Metalloids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Arsenic",
    Symbol: "As",
    AtomicNumber: 33,
    AtomicMass: 74.922,
    Classification: "Metalloids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Selenium",
    Symbol: "Se",
    AtomicNumber: 34,
    AtomicMass: 78.971,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Bromine",
    Symbol: "Br",
    AtomicNumber: 35,
    AtomicMass: 79.904,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Liquid",
  },
  {
    Name: "Krypton",
    Symbol: "Kr",
    AtomicNumber: 36,
    AtomicMass: 83.798,
    Classification: "Noble_gases",
    StateOfMatter: "Gas",
  },
  {
    Name: "Rubidium",
    Symbol: "Rb",
    AtomicNumber: 37,
    AtomicMass: 85.468,
    Classification: "Alkali_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Strontium",
    Symbol: "Sr",
    AtomicNumber: 38,
    AtomicMass: 87.62,
    Classification: "Alkali_earth_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Yttrium",
    Symbol: "Y",
    AtomicNumber: 39,
    AtomicMass: 88.906,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Zirconium",
    Symbol: "Zr",
    AtomicNumber: 40,
    AtomicMass: 91.224,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Niobium",
    Symbol: "Nb",
    AtomicNumber: 41,
    AtomicMass: 92.906,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Molybdenum",
    Symbol: "Mo",
    AtomicNumber: 42,
    AtomicMass: 95.95,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Technetium",
    Symbol: "Tc",
    AtomicNumber: 43,
    AtomicMass: 98,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Ruthenium",
    Symbol: "Ru",
    AtomicNumber: 44,
    AtomicMass: 101.07,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Rhodium",
    Symbol: "Rh",
    AtomicNumber: 45,
    AtomicMass: 102.91,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Palladium",
    Symbol: "Pd",
    AtomicNumber: 46,
    AtomicMass: 106.42,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Silver",
    Symbol: "Ag",
    AtomicNumber: 47,
    AtomicMass: 107.87,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Cadmium",
    Symbol: "Cd",
    AtomicNumber: 48,
    AtomicMass: 112.41,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Indium",
    Symbol: "In",
    AtomicNumber: 49,
    AtomicMass: 114.82,
    Classification: "Post_transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Tin",
    Symbol: "Sn",
    AtomicNumber: 50,
    AtomicMass: 118.71,
    Classification: "Post_transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Antimony",
    Symbol: "Sb",
    AtomicNumber: 51,
    AtomicMass: 121.76,
    Classification: "Metalloids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Tellurium",
    Symbol: "Te",
    AtomicNumber: 52,
    AtomicMass: 127.6,
    Classification: "Metalloids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Iodine",
    Symbol: "I",
    AtomicNumber: 53,
    AtomicMass: 126.9,
    Classification: "Reactive_nonmetals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Xenon",
    Symbol: "Xe",
    AtomicNumber: 54,
    AtomicMass: 131.29,
    Classification: "Noble_gases",
    StateOfMatter: "Gas",
  },
  {
    Name: "Caesium",
    Symbol: "Cs",
    AtomicNumber: 55,
    AtomicMass: 132.91,
    Classification: "Alkali_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Barium",
    Symbol: "Ba",
    AtomicNumber: 56,
    AtomicMass: 137.33,
    Classification: "Alkali_earth_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "57-71*",
    Symbol: "",
    AtomicNumber: null,
    AtomicMass: null,
    Classification: "AtomicNumber_range",
  },
  {
    Name: "Hafnium",
    Symbol: "Hf",
    AtomicNumber: 72,
    AtomicMass: 178.49,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Tantalum",
    Symbol: "Ta",
    AtomicNumber: 73,
    AtomicMass: 180.95,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Tungsten",
    Symbol: "W",
    AtomicNumber: 74,
    AtomicMass: 95.95,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Rhenium",
    Symbol: "Re",
    AtomicNumber: 75,
    AtomicMass: 186.21,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Osmium",
    Symbol: "Os",
    AtomicNumber: 76,
    AtomicMass: 190.23,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Iridium",
    Symbol: "Ir",
    AtomicNumber: 77,
    AtomicMass: 192.22,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Platinum",
    Symbol: "Pt",
    AtomicNumber: 78,
    AtomicMass: 195.08,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Gold",
    Symbol: "Au",
    AtomicNumber: 79,
    AtomicMass: 196.97,
    Classification: "Transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Mercury",
    Symbol: "Hg",
    AtomicNumber: 80,
    AtomicMass: 200.59,
    Classification: "Transition_metals",
    StateOfMatter: "Liquid",
  },
  {
    Name: "Thallium",
    Symbol: "Tl",
    AtomicNumber: 81,
    AtomicMass: 204.38,
    Classification: "Post_transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Lead",
    Symbol: "Pb",
    AtomicNumber: 82,
    AtomicMass: 207.2,
    Classification: "Post_transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Bismuth",
    Symbol: "Bi",
    AtomicNumber: 83,
    AtomicMass: 208.98,
    Classification: "Post_transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Polonium",
    Symbol: "Po",
    AtomicNumber: 84,
    AtomicMass: 209,
    Classification: "Post_transition_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Astatine",
    Symbol: "At",
    AtomicNumber: 85,
    AtomicMass: 210,
    Classification: "Metalloids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Radon",
    Symbol: "Rn",
    AtomicNumber: 86,
    AtomicMass: 222,
    Classification: "Noble_gases",
    StateOfMatter: "Gas",
  },
  {
    Name: "Francium",
    Symbol: "Fr",
    AtomicNumber: 87,
    AtomicMass: 223,
    Classification: "Alkali_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "Radium",
    Symbol: "Ra",
    AtomicNumber: 88,
    AtomicMass: 226,
    Classification: "Alkali_earth_metals",
    StateOfMatter: "Solid",
  },
  {
    Name: "89-103**",
    Symbol: "",
    AtomicNumber: null,
    AtomicMass: null,
    Classification: "AtomicNumber_range",
  },
  {
    Name: "Rutherfordium",
    Symbol: "Rf",
    AtomicNumber: 104,
    AtomicMass: 267,
    Classification: "Transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Dubnium",
    Symbol: "Db",
    AtomicNumber: 105,
    AtomicMass: 268,
    Classification: "Transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Seaborgium",
    Symbol: "Sg",
    AtomicNumber: 106,
    AtomicMass: 269,
    Classification: "Transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Bohrium",
    Symbol: "Bh",
    AtomicNumber: 107,
    AtomicMass: 270,
    Classification: "Transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Hassium",
    Symbol: "Hs",
    AtomicNumber: 108,
    AtomicMass: 277,
    Classification: "Transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Meitnerium",
    Symbol: "Mt",
    AtomicNumber: 109,
    AtomicMass: 278,
    Classification: "Transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Darmstadtium",
    Symbol: "Ds",
    AtomicNumber: 110,
    AtomicMass: 281,
    Classification: "Transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Roentgenium",
    Symbol: "Rg",
    AtomicNumber: 111,
    AtomicMass: 282,
    Classification: "Transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Copernicium",
    Symbol: "Cn",
    AtomicNumber: 112,
    AtomicMass: 285,
    Classification: "Transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Nihonium",
    Symbol: "Nh",
    AtomicNumber: 113,
    AtomicMass: 286,
    Classification: "Post_transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Flerovium",
    Symbol: "Fl",
    AtomicNumber: 114,
    AtomicMass: 289,
    Classification: "Post_transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Moscovium",
    Symbol: "Mc",
    AtomicNumber: 115,
    AtomicMass: 290,
    Classification: "Post_transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Livermorium",
    Symbol: "Lv",
    AtomicNumber: 116,
    AtomicMass: 293,
    Classification: "Post_transition_metals",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Tennessine",
    Symbol: "Ts",
    AtomicNumber: 117,
    AtomicMass: 294,
    Classification: "Metalloids",
    StateOfMatter: "Unknown",
  },
  {
    Name: "Oganesson",
    Symbol: "Og",
    AtomicNumber: 118,
    AtomicMass: 294,
    Classification: "Noble_gases",
    StateOfMatter: "Unknown",
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    Symbol: "*",
    Classification: "range",
    emptyCard: true,
  },
  {
    Name: "Lanthanum",
    Symbol: "La",
    AtomicNumber: 57,
    AtomicMass: 138.91,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Cerium",
    Symbol: "Ce",
    AtomicNumber: 58,
    AtomicMass: 140.12,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Praseodymium",
    Symbol: "Pr",
    AtomicNumber: 59,
    AtomicMass: 140.91,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Neodymium",
    Symbol: "Nd",
    AtomicNumber: 60,
    AtomicMass: 144.24,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Promethium",
    Symbol: "Pm",
    AtomicNumber: 61,
    AtomicMass: 145,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Samarium",
    Symbol: "Sm",
    AtomicNumber: 62,
    AtomicMass: 150.36,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Europium",
    Symbol: "Eu",
    AtomicNumber: 63,
    AtomicMass: 151.96,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Gadolinium",
    Symbol: "Gd",
    AtomicNumber: 64,
    AtomicMass: 157.25,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Terbium",
    Symbol: "Tb",
    AtomicNumber: 65,
    AtomicMass: 158.93,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Dysprosium",
    Symbol: "Dy",
    AtomicNumber: 66,
    AtomicMass: 162.5,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Holmium",
    Symbol: "Ho",
    AtomicNumber: 67,
    AtomicMass: 164.93,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Erbium",
    Symbol: "Er",
    AtomicNumber: 68,
    AtomicMass: 167.26,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Thulium",
    Symbol: "Tm",
    AtomicNumber: 69,
    AtomicMass: 168.93,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Ytterbium",
    Symbol: "Yb",
    AtomicNumber: 70,
    AtomicMass: 173.05,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Lutetium",
    Symbol: "Lu",
    AtomicNumber: 71,
    AtomicMass: 174.97,
    Classification: "Lanthanoids",
    StateOfMatter: "Solid",
  },
  {
    emptyCard: true,
  },
  {
    emptyCard: true,
  },
  {
    Symbol: "**",
    Classification: "range",
    emptyCard: true,
  },
  {
    Name: "Actinium",
    Symbol: "Ac",
    AtomicNumber: 89,
    AtomicMass: 227,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Thorium",
    Symbol: "Th",
    AtomicNumber: 90,
    AtomicMass: 232.04,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Protactinium",
    Symbol: "Pa",
    AtomicNumber: 91,
    AtomicMass: 231.04,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Uranium",
    Symbol: "U",
    AtomicNumber: 92,
    AtomicMass: 238.03,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Neptunium",
    Symbol: "Np",
    AtomicNumber: 93,
    AtomicMass: 237,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Plutonium",
    Symbol: "Pu",
    AtomicNumber: 94,
    AtomicMass: 244,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Americium",
    Symbol: "Am",
    AtomicNumber: 95,
    AtomicMass: 243,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Curium",
    Symbol: "Cm",
    AtomicNumber: 96,
    AtomicMass: 247,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Berkelium",
    Symbol: "Bk",
    AtomicNumber: 97,
    AtomicMass: 247,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Californium",
    Symbol: "Cf",
    AtomicNumber: 98,
    AtomicMass: 251,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Einsteinium",
    Symbol: "Es",
    AtomicNumber: 99,
    AtomicMass: 252,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Fermium",
    Symbol: "Fm",
    AtomicNumber: 100,
    AtomicMass: 257,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Mendelevium",
    Symbol: "Md",
    AtomicNumber: 101,
    AtomicMass: 258,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Nobelium",
    Symbol: "No",
    AtomicNumber: 102,
    AtomicMass: 259,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
  {
    Name: "Lawrencium",
    Symbol: "Lr",
    AtomicNumber: 103,
    AtomicMass: 266,
    Classification: "Actinoids",
    StateOfMatter: "Solid",
  },
];
